controllers:
    resource: '../../src/Controller/'
    type: attribute

api_doc:
    path: /api/docs
    controller: nelmio_api_doc.controller.swagger_json

swagger_ui:
    path: /swagger
    controller: nelmio_api_doc.controller.swagger
